[package]
name = "tricore-emu"
version = "0.1.0"
authors = ["Matthew Alonso <granjef3@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
